export const postSeedData = [
    { "title": "Post Title 1", "content": "This is the content for post 1", "userId": 1 },
    { "title": "Post Title 2", "content": "This is the content for post 2", "userId": 2 },
    { "title": "Post Title 3", "content": "This is the content for post 3", "userId": 3 },
    { "title": "Post Title 4", "content": "This is the content for post 4", "userId": 4 },
    { "title": "Post Title 5", "content": "This is the content for post 5", "userId": 5 },
    { "title": "Post Title 6", "content": "This is the content for post 6", "userId": 6 },
    { "title": "Post Title 7", "content": "This is the content for post 7", "userId": 7 },
    { "title": "Post Title 8", "content": "This is the content for post 8", "userId": 8 },
    { "title": "Post Title 9", "content": "This is the content for post 9", "userId": 9 },
    { "title": "Post Title 10", "content": "This is the content for post 10", "userId": 10 },
    { "title": "Post Title 11", "content": "This is the content for post 11", "userId": 11 },
    { "title": "Post Title 12", "content": "This is the content for post 12", "userId": 12 },
    { "title": "Post Title 13", "content": "This is the content for post 13", "userId": 13 },
    { "title": "Post Title 14", "content": "This is the content for post 14", "userId": 14 },
    { "title": "Post Title 15", "content": "This is the content for post 15", "userId": 15 },
    { "title": "Post Title 16", "content": "This is the content for post 16", "userId": 16 },
    { "title": "Post Title 17", "content": "This is the content for post 17", "userId": 17 },
    { "title": "Post Title 18", "content": "This is the content for post 18", "userId": 18 },
    { "title": "Post Title 19", "content": "This is the content for post 19", "userId": 19 },
    { "title": "Post Title 20", "content": "This is the content for post 20", "userId": 20 }
]
